# Step 1: Build stage
FROM maven:3.8.5-openjdk-17 AS build
WORKDIR /app
# Humare case mein pom.xml nested hai, isliye hum saara maal copy kar rahe hain
COPY . .
# Ye command aapke nested folder mein jaakar build karegi
RUN mvn -f shiksha/shiksha/pom.xml clean package -DskipTests

# Step 2: Run stage
FROM openjdk:17-jdk-slim
WORKDIR /app
# Build stage se jar file uthao
COPY --from=build /app/shiksha/shiksha/target/*.jar app.jar
EXPOSE 8080
ENTRYPOINT ["java","-jar","app.jar"]